#!/usr/bin/env python3
"""Writes sps_fixtures.inc: real H.264 SPS NAL units made by x264, with what ffprobe says they are.

    python3 make_sps.py            (needs ffmpeg with libx264 and ffprobe)

Each fixture is the first SPS of a one-frame stream.  The expectations come from ffprobe, not from the
code under test (tests/test_h264_sps.cpp).
"""
import json
import os
import subprocess
import sys
import tempfile

# name, size, ffmpeg options, expected frame rate (None = x264 writes none)
CASES = [
    ("baseline_64",     "64x64",     "-profile:v baseline -level 3.0 -r 25",                      25.0),
    ("main_720p_24",    "1280x720",  "-profile:v main -level 3.1 -r 24000/1001",                  24000 / 1001),
    ("high_1080p_24",   "1920x1080", "-profile:v high -level 4.1 -r 24000/1001",                  24000 / 1001),
    ("high_1080p_60",   "1920x1080", "-profile:v high -level 4.2 -r 60",                          60.0),
    ("high_1080i",      "1920x1080", "-profile:v high -level 4.1 -r 25 -flags +ilme+ildct -x264opts tff=1", 25.0),
    ("main_480p_ntsc",  "720x480",   "-profile:v main -level 3.0 -r 30000/1001",                  30000 / 1001),
    ("baseline_768",    "1366x768",  "-profile:v baseline -level 3.1 -r 30",                      30.0),
    ("high10_1080p",    "1920x1080", "-profile:v high10 -level 4.1 -pix_fmt yuv420p10le -r 24",   24.0),
    ("high422_1080p",   "1920x1080", "-profile:v high422 -level 4.1 -pix_fmt yuv422p -r 24",      24.0),
    ("high_4k",         "3840x2160", "-profile:v high -level 5.1 -r 24",                          24.0),
    ("high_1080p_l51",  "1920x1080", "-profile:v high -level 5.1 -r 24",                          24.0),
]


def run(cmd):
    return subprocess.run(cmd, shell=True, check=True, capture_output=True)


def first_sps(es):
    i = 0
    while True:
        i = es.find(b"\x00\x00\x01", i)
        if i < 0:
            return None
        if es[i + 3] & 0x1F == 7:
            j = es.find(b"\x00\x00\x01", i + 3)
            nal = es[i + 3:j if j >= 0 else len(es)]
            return nal.rstrip(b"\x00")
        i += 3


def main():
    out = []
    with tempfile.TemporaryDirectory() as d:
        for name, size, opts, fps in CASES:
            es = os.path.join(d, name + ".h264")
            vf = "-pix_fmt yuv420p " if "pix_fmt" not in opts else ""
            run("ffmpeg -v error -y -f lavfi -i testsrc=size=%s:rate=24 -frames:v 1 -c:v libx264 %s%s -bsf:v h264_mp4toannexb -f h264 %s"
                % (size, vf, opts, es))
            nal = first_sps(open(es, "rb").read())
            if not nal:
                sys.exit("no SPS for " + name)
            probe = json.loads(run("ffprobe -v error -select_streams v:0 -show_entries "
                                   "stream=width,height,profile,level,pix_fmt,field_order -of json %s" % es).stdout)["streams"][0]
            out.append((name, nal, probe, fps))
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "sps_fixtures.inc"), "w") as f:
        f.write("// Generated by make_sps.py (ffmpeg + libx264, expectations from ffprobe).  Do not edit.\n")
        f.write("// name, nal bytes, width, height, level_idc, bit depth, chroma_format_idc, frame_mbs_only, fps\n")
        for name, nal, p, fps in out:
            depth = 10 if "10" in p["pix_fmt"] else 8
            chroma = 2 if "422" in p["pix_fmt"] else 1
            interlaced = p.get("field_order", "progressive") not in ("progressive", "unknown")
            f.write("{ \"%s\", { %s }, %d, %d, %d, %d, %d, %d, %d, %.6f, %s },\n" % (
                name, ", ".join("0x%02x" % b for b in nal), len(nal), p["width"], p["height"],
                p["level"], depth, chroma, 0 if interlaced else 1, fps, '"%s"' % p["profile"]))
            print(name, p["width"], p["height"], p["profile"], p["level"], p["pix_fmt"], p.get("field_order"), len(nal))


if __name__ == "__main__":
    main()
