#!/usr/bin/env python3
"""Subset Noto Sans JP into the glyphs the app can ask for, and write it as a C header.

    python tools/gen_jp_font.py NotoSansJP-Regular.otf [--level 1|2] [--out source/gfx/notosansjp.h]

Needs fontTools (pip install fonttools).  The glyph set is:
  * every character the interface catalog uses that Latin-1 does not cover (tools/i18n.py chars),
  * kana, the CJK punctuation block and the full-width forms,
  * the JIS X 0208 symbol rows, and the kanji of JIS level 1 (--level 1, 2,965 characters: what a
    Japanese title or name is written in nearly always) or level 1 + 2 (--level 2, 6,355).
The server's titles are drawn in whatever Latin face the role has, and fall back to this face for
what that face lacks (ui_text.cpp, chain_of), so a Japanese title shows instead of being dropped.
Noto Sans JP is SIL OFL 1.1; see source/gfx/fonts/LICENSES.md.
"""
import argparse, os, subprocess, sys, tempfile

ap = argparse.ArgumentParser()
ap.add_argument('font')
ap.add_argument('--level', type=int, default=1, choices=(1, 2))
ap.add_argument('--out', default=os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'source', 'gfx', 'notosansjp.h'))
ap.add_argument('--chars', default=None, help='file with the catalog characters (default: run tools/i18n.py chars)')
args = ap.parse_args()

here = os.path.dirname(os.path.abspath(__file__))
chars = set()


def sjis(first, last):
    """Characters of JIS X 0208 rows first..last (1-based), through the Shift_JIS codec."""
    for row in range(first, last + 1):
        for cell in range(1, 95):
            j1, j2 = 0x20 + row, 0x20 + cell
            # JIS -> Shift_JIS
            if row % 2:
                s1 = (j1 + 1) // 2 + (0x70 if j1 < 0x5F else 0xB0)
                s2 = j2 + (0x1F if j2 < 0x60 else 0x20)
            else:
                s1 = j1 // 2 + (0x70 if j1 < 0x5F else 0xB0)
                s2 = j2 + 0x7E
            try:
                chars.add(bytes([s1, s2]).decode('shift_jis'))
            except UnicodeDecodeError:
                pass


sjis(1, 8)                                  # symbols, digits, Latin, kana, Greek, Cyrillic, box drawing
sjis(16, 47 if args.level == 1 else 84)     # kanji
chars.update(chr(c) for c in range(0x3000, 0x3100))     # CJK punctuation, hiragana, katakana
chars.update(chr(c) for c in range(0xFF00, 0xFFF0))     # full-width forms
chars.update(chr(c) for c in range(0x2010, 0x2030))     # dashes, quotes, bullets
chars.update('〜～・·×÷○●◎◇◆□■△▲▽▼→←↑↓※€')
if args.chars:
    cat = open(args.chars, encoding='utf-8').read()
else:
    cat = subprocess.run([sys.executable, os.path.join(here, 'i18n.py'), 'chars'], capture_output=True, text=True,
                         encoding='utf-8').stdout
chars.update(cat)
chars.discard('\n')
print('%d characters requested' % len(chars))

with tempfile.TemporaryDirectory() as tmp:
    txt = os.path.join(tmp, 'chars.txt')
    out = os.path.join(tmp, 'subset.otf')
    open(txt, 'w', encoding='utf-8').write(''.join(sorted(chars)))
    subprocess.check_call([sys.executable, '-m', 'fontTools.subset', args.font, '--text-file=' + txt, '--output-file=' + out,
                           '--layout-features=', '--no-hinting', '--drop-tables+=DSIG,vhea,vmtx,VORG,GSUB,GPOS,GDEF,BASE',
                           '--name-IDs=', '--notdef-outline'])
    data = open(out, 'rb').read()
print('subset: %d bytes' % len(data))

lines = ['// Generated by tools/gen_jp_font.py from NotoSansJP-Regular.otf -- do NOT edit by hand.',
         '// Subset to what the interface catalog uses plus kana, punctuation and JIS X 0208 level %d kanji.' % args.level,
         '// Noto Sans JP, SIL Open Font License 1.1: see source/gfx/fonts/LICENSES.md.',
         'unsigned char NotoSansJP_otf[] = {']
for i in range(0, len(data), 16):
    lines.append('  ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
lines.append('};')
lines.append('unsigned int NotoSansJP_otf_len = %d;' % len(data))
open(args.out, 'w', newline='\n').write('\n'.join(lines) + '\n')
print('wrote', os.path.normpath(args.out))
