#!/usr/bin/env python3
"""Tessellate the Jellyfin logo into source/ui/render/jf_logo_geom.h.

The mark is two shapes from Jellyfin's icon-transparent.svg (viewBox 512x512):
an arch -- the outer rounded triangle with a triangular hole -- and the small
solid triangle inside it.  Both are star-shaped about a point near their
middle, so each boundary is resampled at N equal angles from that point:

  * the arch becomes ONE triangle strip, outer[i] / hole[i] pairs;
  * the small triangle becomes ONE fan from its centre.

That is 2*(N+1) + (M+2) vertices for the whole mark, drawn in immediate mode
on the wave's passthrough programs (ui_wave_panels.cpp), coloured per vertex
with the logo's purple -> blue gradient.  No texture, no alpha blit, crisp at
any size.

Coordinates are written centred on the mark and scaled so the arch's half
width is 1.0 (x right, y DOWN, as on screen).

    python3 tools/gen_jf_logo_geom.py > source/ui/render/jf_logo_geom.h
"""
import math, re

INNER = "M190.56 329.07c8.63 17.3 122.4 17.12 130.93 0 8.52-17.1-47.9-119.78-65.46-119.8-17.57 0-74.1 102.5-65.47 119.8z"
OUTER = ("M58.75 417.03c25.97 52.15 368.86 51.55 394.55 0S308.93 56.08 256.03 56.08"
         "c-52.92 0-223.25 308.8-197.28 360.95z"
         "m68.04-45.25c-17.02-34.17 94.6-236.5 129.26-236.5 34.67 0 146.1 202.7 "
         "129.26 236.5-16.83 33.8-241.5 34.17-258.52 0z")

def parse(d):
    toks = re.findall(r"[MmCcSsZz]|-?\d*\.?\d+(?:e-?\d+)?", d)
    i, cmd = 0, None
    cur = (0.0, 0.0); start = cur; last_c2 = None
    polys, poly = [], []
    def num():
        nonlocal i
        v = float(toks[i]); i += 1; return v
    def cubic(p0, p1, p2, p3):
        for k in range(1, 25):
            t = k / 24.0; u = 1 - t
            poly.append((u*u*u*p0[0] + 3*u*u*t*p1[0] + 3*u*t*t*p2[0] + t*t*t*p3[0],
                         u*u*u*p0[1] + 3*u*u*t*p1[1] + 3*u*t*t*p2[1] + t*t*t*p3[1]))
    while i < len(toks):
        if re.match(r"[A-Za-z]", toks[i]):
            cmd = toks[i]; i += 1
            if cmd in "Zz":
                if poly: polys.append(poly)
                poly = []; cur = start; last_c2 = None
                continue
        rel = cmd.islower()
        ox, oy = cur if rel else (0.0, 0.0)
        if cmd in "Mm":
            cur = (ox + num(), oy + num()); start = cur; poly = [cur]; last_c2 = None
            cmd = "l" if rel else "L"   # not used by these paths
        elif cmd in "Cc":
            p1 = (ox + num(), oy + num()); p2 = (ox + num(), oy + num()); p3 = (ox + num(), oy + num())
            cubic(cur, p1, p2, p3); last_c2 = p2; cur = p3
        elif cmd in "Ss":
            p1 = (2*cur[0] - last_c2[0], 2*cur[1] - last_c2[1]) if last_c2 else cur
            p2 = (ox + num(), oy + num()); p3 = (ox + num(), oy + num())
            cubic(cur, p1, p2, p3); last_c2 = p2; cur = p3
        else:
            raise SystemExit("unsupported command " + cmd)
    if poly: polys.append(poly)
    return polys

def ray_hit(poly, c, ang):
    dx, dy = math.cos(ang), math.sin(ang)
    best = None
    n = len(poly)
    for k in range(n):
        ax, ay = poly[k]; bx, by = poly[(k + 1) % n]
        ex, ey = bx - ax, by - ay
        den = dx * ey - dy * ex
        if abs(den) < 1e-12: continue
        t = ((ax - c[0]) * ey - (ay - c[1]) * ex) / den
        s = ((ax - c[0]) * dy - (ay - c[1]) * dx) / den
        if t > 0 and -1e-9 <= s <= 1 + 1e-9:
            if best is None or t > best: best = t   # farthest crossing
    if best is None: raise SystemExit("ray missed")
    return (c[0] + dx * best, c[1] + dy * best)

def centroid(poly):
    return (sum(p[0] for p in poly) / len(poly), sum(p[1] for p in poly) / len(poly))

outer_polys = parse(OUTER)
outer, hole = outer_polys[0], outer_polys[1]
inner = parse(INNER)[0]

N, M = 96, 48
c_arch = centroid(hole)
c_in = centroid(inner)
angs = [2 * math.pi * k / N for k in range(N)]
o_s = [ray_hit(outer, c_arch, a) for a in angs]
h_s = [ray_hit(hole, c_arch, a) for a in angs]
i_s = [ray_hit(inner, c_in, 2 * math.pi * k / M) for k in range(M)]

xs = [p[0] for p in outer]; ys = [p[1] for p in outer]
cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
half = (max(xs) - min(xs)) / 2
def n(p): return ((p[0] - cx) / half, (p[1] - cy) / half)

def arr(name, pts):
    out = "static const float %s[%d][2] = {\n" % (name, len(pts))
    for k in range(0, len(pts), 3):
        out += "    " + " ".join("{ %9.6ff, %9.6ff }," % n(p) for p in pts[k:k + 3]) + "\n"
    return out + "};\n"

print("// GENERATED by tools/gen_jf_logo_geom.py -- do not edit.")
print("// The Jellyfin mark (icon-transparent.svg), tessellated: the arch as a")
print("// triangle strip of outer/hole pairs, the small triangle as a fan.")
print("// Centred on the mark, arch half-width = 1.0, y down.")
print("#ifndef JF_LOGO_GEOM_H\n#define JF_LOGO_GEOM_H\n")
print("#define JF_LOGO_N %d\n#define JF_LOGO_M %d" % (N, M))
print("static const float JF_LOGO_INNER_C[2] = { %9.6ff, %9.6ff };" % n(c_in))
print("#define JF_LOGO_HALF_H %.6ff\n" % ((max(ys) - min(ys)) / 2 / half))
print(arr("JF_LOGO_OUTER", o_s))
print(arr("JF_LOGO_HOLE", h_s))
print(arr("JF_LOGO_INNER", i_s))
print("#endif")
