#!/usr/bin/env python3
"""Embed the legacy app icon's logo as source/gfx/jf_legacy_icon_png.h.

ICON0.PNG is the original JellyFin-PS3 icon from MontyMcK's upstream project:
the PlayStation mark filled with Jellyfin's purple -> teal gradient.  The
buffering screen draws that logo at its centre, so only the logo is kept --
the image is cropped to its alpha bounding box plus a 2 px margin (so linear
filtering never samples past the edge) and stored as a PNG, decoded once at
runtime by render/ui_buffering.cpp.

    python3 tools/gen_legacy_icon.py > source/gfx/jf_legacy_icon_png.h
"""
import io, os
from PIL import Image

src = os.path.join(os.path.dirname(__file__), "..", "ICON0.PNG")
im = Image.open(src).convert("RGBA")
x0, y0, x1, y1 = im.getchannel("A").getbbox()
pad = 2
box = (max(0, x0 - pad), max(0, y0 - pad), min(im.width, x1 + pad), min(im.height, y1 + pad))
crop = im.crop(box)
buf = io.BytesIO()
crop.save(buf, "PNG", optimize=True)
data = buf.getvalue()

print("// GENERATED by tools/gen_legacy_icon.py from ICON0.PNG -- do not edit.")
print("// The legacy JellyFin-PS3 logo (MontyMcK's original app icon), cropped to")
print("// the logo: %dx%d RGBA, straight alpha.  Decoded once by ui_buffering.cpp." % crop.size)
print("#ifndef JF_LEGACY_ICON_PNG_H\n#define JF_LEGACY_ICON_PNG_H\n")
print("#define JF_LEGACY_ICON_W %d\n#define JF_LEGACY_ICON_H %d\n" % crop.size)
print("static const unsigned char jf_legacy_icon_png[%d] = {" % len(data))
for i in range(0, len(data), 16):
    print("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
print("};\n\n#endif")
